class CreateAtrocities < ActiveRecord::Migration
  def change
    create_table :atrocities do |t|
      t.string :event_type
      t.string :campaign_identifier
      t.string :event_reporting
      t.integer :start_day
      t.integer :start_month
      t.integer :start_year
      t.integer :end_day
      t.integer :end_month
      t.integer :end_year
      t.string :country
      t.string :region
      t.string :district
      t.string :locality
      t.integer :degrees
      t.integer :minutes
      t.integer :seconds
      t.string :direction
      t.string :distance_km
      t.string :direction
      t.string :perp_state_role
      t.string :perp_state_military
      t.string :perp_state_police
      t.string :perp_state_other
      t.string :perp_nonstate_ideological
      t.string :perp_nonstate_ethnic
      t.string :perp_nonstate_religious
      t.string :perp_nonstate_criminal
      t.string :perp_nonstate_private
      t.string :perp_unknown_unclear_other
      t.string :victim_noncombatant_asserted
      t.string :victim_noncombatant_contested
      t.string :victim_identity_political
      t.string :victim_identity_ethnic_national_citizenship
      t.string :victim_identity_religious
      t.string :victim_identity_socio_economic
      t.string :victim_identity_Unarmed_combatants
      t.string :victim_identity_random_unknown_unclear_other
      t.integer :deaths_number
      t.string :deaths_scale
      t.integer :injured_number
      t.string :injured_scale
      t.string :deaths_ambiguity
      t.string :deaths_contested
      t.string :organization_of_violence
      t.string :weapons
      t.string :intent
      t.string :regrets
      t.string :collateral_damage
      t.string :food_aid_as_a_weapon
      t.string :scorched_earth_tactics
      t.string :human_shields
      t.string :rape
      t.string :targeted_assassinations
      t.string :mass_detentions
      t.string :sieges_closures
      t.string :kidnappings
      t.string :disappearances
      t.string :other_Tactics
      t.string :description
      t.string :link
      t.string :primary_source_type
      t.string :primary_source
      t.string :secondary_source_type
      t.string :secondary_source
      t.string :contesting_source_type
      t.string :contesting_Source
      t.string :citation
      t.string :comments
      t.string :coder
    end
  end
end
